JanitorTechnology/janitor

lib/machines.js

Allow spawning multiple containers per project.

---

lib/routes.js

- update Dockerfiles submodule
- fix a leftover FIXME from #47

Quick fixes

---

templates/admin-projects.html

- Update the Dockerfiles submodule to the latest revision.
- Fix a few IDs in the admin project creation form.

Minor fixes

---

api/user-api.js
lib/configurations.js
lib/machines.js
lib/routes.js
lib/users.js
static/css/janitor.css
static/js/janitor.js
templates/settings-configurations.html

In this change I tweak the API and the front-end code to slightly improve the UX of the new "Configurations" panel. This changes:
- The "Configurations" panel now has a short description, and the inputs & buttons are placed more elegantly.
- "Deploy configuration" API now returns the number of modified containers (e.g. "Successfully deployed to 3 containers").
- On the front-end, any `data.message` attribute will be displayed (if there is no error to display instead).

Slightly improve the Configurations settings panel.

---

api/admin-api.js
api/user-api.js
lib/machines.js

The exported method name recently changed to be more explicit.

Fix `jsonpatch.apply()` calls to `jsonpatch.applyPatch()`.

---

lib/db.js
lib/sessions.js

Fixes #93 
I didn't use [proper really random values](https://developer.mozilla.org/en/docs/Web/API/RandomSource/getRandomValues) because it seemed overkill, I can change that if needed ;)

Use a random cookie name

---

lib/sessions.js

Refs #93 and #94 and #97. Hopefully this is working correctly now.

Fix the random cookiename. Again.

---

lib/certificates.js
lib/db.js
lib/metrics.js
lib/streams.js

Refactor exports

---

api/user-api.js
app.js
lib/routes.js
lib/users.js
static/css/janitor.css
static/js/janitor.js
templates/notifications.html
templates/settings-header.html
templates/settings-notifications.html

Implementation for notifications for the Janitor

Implement Notifications

---

api/admin-api.js
api/hosts-api.js
api/user-api.js
lib/machines.js
lib/users.js
static/css/janitor.css
static/js/janitor.js
templates/contributions.html

@jankeromnes, can you take a look please? Cheers!

Allow renaming containers

---

Makefile
README.md

We shall let go of the past and embrace the present.

Tear down most of the Makefile and update README.md.

---

.janitor.json

We recently introduced a `janitor.json` configuration file for projects to specify useful information and common workflow steps to be used on https://janitor.technology.
This depends on https://github.com/JanitorTechnology/c9.ide.janitorconfig/issues/1.

Add a .janitor.json configuration file to this project.

---

app.js

Another bit of fall out from #124.

Fix local proxy for Cloud9 IDE by accepting more URLs.

---

app.js
lib/routes.js
static/css/janitor.css
static/js/admin.js
static/js/graphs.js
templates/admin-docker.html
templates/admin-header.html
templates/admin-projects.html

This new administration interface will help analyzing the disk space captured by older containers that prevent older images from being garbage collected.
I will also add a "Garbage Collect" button to this interface soon.

Add an administration section for Docker images and containers.

---

api/hosts-api.js
lib/machines.js
lib/routes.js

In this pull request, I:
- fix old container names
- slightly improve the container API handlers and their documentation
- make the pages `/` and `/projects/` load faster

A few small fixes.

---

static/js/janitor.js

Don't auto-blur form elements upon submit.

---

lib/machines.js
static/css/janitor.css
static/js/janitor.js
templates/contributions.html

Fix feedback when deleting containers

---

lib/users.js

feel free to close it if changes doesn't make sense.

Adding port to sign-in link if hostname is localhost.

---

Makefile
README.md
static/manifest.json
templates/footer.html
templates/header.html
templates/landing.html

@jankeromnes I have renamed `The Janitor` to `Janitor` everywhere except on blogs page but please do a double check.

renaming The Janitor to Janitor

---

templates/projects.html

I found more code that was using `/contributions`. 
@jankeromnes If you have time to review this short edit. 
Continuation of https://github.com/JanitorTechnology/janitor/pull/169

Use new containers directory

---

join.js

When you use a Janitor proxy for the first time (i.e. you have no authentication cookie for that particular proxy host), a "transparent" OAuth2 round-trip happens with the main janitor.technology app in order to authenticate you.
But when your very first proxy request is finally authenticated, you're left with two additional parameters in your URL, something like `?code=1234&state=5678`. The problem is that these parameters are single-use, and by the time you see the requested page appear, they're already expired.
This means that if you try to refresh the page (with both parameters still in the URL), the proxy will consider this a login attempt, but reject the expired code and state, resulting in a "403 Forbidden" page.
The solution against this is, for URLs like …

Automatically remove used OAuth2 code and state parameters from proxy URLs.

---

lib/machines.js
package-lock.json
templates/projects.html

Added project description

---

.janitor.json

https://github.com/JanitorTechnology/c9.ide.janitorconfig/pull/9

Mark the "Preview" port as the "preview" port

---

README.md

Hi,
I have added an instruction for local installation about `db.json`.
Issue https://github.com/JanitorTechnology/janitor/issues/183

Add instruction for local installation

---

app.js
lib/routes.js
static/css/janitor-new.css
static/img/icons/edit.svg
templates/containers-new.html
templates/design.html

This page shows the appearance of all of the widgets that have been styled.

Design page

---

templates/configurations/.gitconfig
templates/containers-new.html

Fixes #212 and new containers page delete button.

Small fixes

---

app.js
join.js
lib/hosts.js
lib/oauth2.js

This is easier to review with `?w=1` to ignore whitespace changes, e.g. https://github.com/JanitorTechnology/janitor/pull/220/files?w=1

Refactor container proxy OAuth2 authentication to async/await.

---

api/blog-api.js

Makes the Discourse webhook actually work right.

Switch the blog handler over to POST

---

lib/blog.js

With some minor drive-by clean up.
@notriddle please have a look when you have a minute. 😄

Log Discourse API errors more explicitly.

---

app.js
lib/users.js
static/js/settings.js
templates/settings-account.html
templates/settings-integrations.html

A little Thursday-morning clean-up.

Remove third-party c9.io integration because we no longer use it.

---

static/css/janitor-new.css
templates/footer-new.html

- Fixed the container page panel shadows
- remove unnecessary uses of flexbox
- remove the `gray-text` class
- Fixed blog page main container
- Slightly reduce the header height (I think it was a bit too large)

New design tweaks

---

README.md

Using the amazing https://david-dm.org/ service.

Add NPM dependencies status badge to README.md.

---

app.js
lib/routes.js
static/css/janitor-new.css
templates/404-new.html

New 404 page

---

app.js
lib/routes.js
static/css/janitor-new.css
templates/header-new.html
templates/login-new.html

New login page

---

lib/routes.js
static/css/janitor-new.css
static/img/icons/arrow-down.svg
static/img/icons/arrow-up.svg
static/js/blog-new.js
static/js/janitor-new.js
templates/blog-new.html

Blog page tweaks

---

templates/header.html

Old-design front page:
Old-design containers page:

Add temporary website banner mentioning the 2018 Janitor survey.

---

lib/routes.js
static/css/janitor-new.css
static/img/icons/warning.svg
templates/404-new.html
templates/blog-new.html
templates/containers-new.html
templates/data-new.html
templates/design.html
templates/footer-new.html
templates/header-insecure-new.html
templates/header-new.html
templates/login-new.html
templates/project-new.html
templates/projects-new.html
templates/reference-api-new.html
templates/settings-new.html

Remove main from header and reposition warning-alert.

---

Makefile

Security fixes

---

templates/configurations/.hgrc

(still blocked on https://github.com/JanitorTechnology/dockerfiles/pull/175)

hgrc: add fsmonitor

---

static/img/privatebin.svg

This pull request relates to this one:
https://github.com/JanitorTechnology/dockerfiles/pull/199
I would like to add PrivateBin as a Janitor project.

adding PrivateBin logo

---

lib/docker.js

I wasn't able to try this in my local janitor container. Please test first.
@jankeromnes

Set mode to 0600 to all config files

---

static/css/janitor-new.css

Use a nicer way to save space in cards

---

lib/blog.js
static/css/blog.css

Blog fixes

---

README.md

Add DataDog Sponsorship to README

---

app.js
lib/routes.js
templates/about.html
templates/footer.html

This is a initial implementation of #5. I wanted to get the mechanics of the page working and make sure those are done properly from the start.

Add About Page

---

package.json

fix(package): update selfapi to version 1.0.0

---

lib/blog.js

This prevents topics from being un-published
https://discourse.janitor.technology/t/our-latest-newsletter-janitor-news-11-keeps-getting-unpublished/241

Order topics by creation instead of update

---

.github/workflows/ci.yml
.travis.yml
README.md

Travis is quite slow. Github Actions is integrated and instantaneous.

Replace Travis with Github Actions

---

.github/renovate.json
renovate.json

Quite annoying to merge manually, so setting minor updates and devDependencies to auto-merge when possible.

Auto-merge Renovate commits
