JanitorTechnology/janitor

app.js
join.js
lib/routes.js
package.json

In theory, there should be no functional change here (except for the small `http.ServerResponse` bug-fix I sneaked in).
This pull request switches to [ScoutCamp](https://github.com/espadrine/sc)'s new preferred way to deal with templates, which allows pre-compiling templates with `camp.template()`, and serving templated responses by calling `response.template()` directly instead of relying on `camp.route()`'s `end()` callback (note: `camp.route()` is slowly being deprecated, as is `query`: eventually, every route should use `camp.path(pattern, (request, response) => {})`, but this will happen in future pull requests).
@bnjbvr, could you please verify that I didn't make any obvious mistakes?
@espadrine, could you please have a look at how I handle templates, and if this the fastest way to …

Refactor server response routes in order to pre-compile all templates.

---

app.js
join.js
lib/boot.js
lib/routes.js
lib/sessions.js
lib/users.js
templates/header-insecure.html

This pull request introduces two `db.json` security parameters:
```json
{
"security": {
"forceHttp": true,
"forceInsecure": true
}
}
```
They can be used by Janitor developers to completely disable HTTPS support, Let's Encrypt certificate generation, and several security policies (like hostname verification and some HTTP headers).
Additionally, forcing "insecure mode" adds an obvious warning message to all web pages, so that any accident on a production app becomes immediately visible to all users.
It also prints all sign-in keys in the server logs, because signing in via email is generally not an option when developing locally.
Note: I also sneaked in the unrelated `http.ServerResponse` bug fix again, respecting your nits from the previous pull request. Sorry for making the diff view …

Allow forcing insecure HTTP for local development only

---

.gitignore

@jankeromnes I was working on submitting the last PR when I encountered files from the `.c9/` added to my list of watched files. I heard that `.gitignore` can prevent files and folders from being pushed upstream so I made an addition to the `.gitignore` file. Let me know what you think.

Ignore the  folder when making git commands

---

app.js
join.js
lib/routes.js
package.json

This uses `saveRequestChunks`, a new ScoutCamp feature added in https://github.com/espadrine/sc/pull/60, and partially fixes #54.

Make the web proxy re-send any previously consumed data chunks

---

api/hosts-api.js
api/index.js
app.js
lib/routes.js
static/css/janitor.css
templates/footer.html
templates/reference-api.html

This simple change just adds a small template that includes `api.toHTML()`, which is a basic HTML export of Janitor's live [SelfAPI](https://github.com/JanitorTechnology/selfapi) instance. I also added a few basic CSS rules to make these docs more readable.
The resulting page looks like this:
Edit: I've also added another commit with a few minor fixes (coding style, API description).

Add an automatically generated API reference page to the website.

---

lib/users.js

- I address a usability issue (helpful for developing Janitor in Janitor) that allows admin users to sign in without invitation. (Without this, one first needs to forcibly call `getOrCreate('admin@localhost')` in `/lib/users.js` before being able to sign in.)
- I include a few more commits from the [dockerfiles](https://github.com/JanitorTechnology/dockerfiles) repository in our submodule.

Minor changes.

---

api/admin-api.js
api/index.js

This pull requests adds two API endpoints (that will be used in a follow-up pull request to support authentication via GitHub):
- List all OAuth2 provider configurations (their URLs and client credentials)
- Update an OAuth2 provider (accepting a JSON body formatted as an RFC 6902 JSON Patch array)
They should only be usable by website administrators (note the `users.isAdmin(user)` checks), and should fail otherwise.
The SelfAPI auto-generated documentation looks like this:

Add an API to manage third-party OAuth2 providers.

---

api/index.js
api/user-api.js
lib/users.js
templates/settings-account.html

This pull request adds a `/api/user` endpoint which allows `GET` and `PATCH` operations to manage the current user's profile information.
Behind the scenes, it manages a newly introduced `user.profile = { name: '' }` object, which the user will be able to change at will. (In the future, it might contains things like avatar url, website, short bio, etc. if deemed useful).
The auto-generated User API docs look like this with this commit:

Add an API to manage users, and use it to edit real names

---

lib/machines.js

The status `filter` was wrongly applied to the Array of project machines *before* they were `reduce`d to a single Array of machines. The structure looks like this:
```js
user.machines = {
"firefox": [ machine0, machine1 ],
"chromium": [ machine0 ],
}
```
The existing code was wrongly checking `[ machine0, machine1 ].status === 'started'`, which doesn't work because an Array has no "status" property.
The fix is to make multiple `machine0.status === 'started'` checks on all machines.

Fix deploying configuration files to all containers.

---

lib/sessions.js

Fix a forgotten hard-coded "token" cookie name that was left over from #94.

Use a random cookie name 2/2.

---

app.js

This would allow accessing https://janitor.technology/projects/firefox-hg/ (currently 404).

Accept '-' in project IDs for project page URLs.

---

app.js
join.js
lib/routes.js
package.json

Hooray! We're finally switching our server back to [camp](https://www.npmjs.com/package/camp) from the infamous [@jankeromnes/camp](https://www.npmjs.com/package/@jankeromnes/camp) fork introduced in a8df359f058c5480cbd730c089f9478ae0df5397 and c11bb4280bbeb73b071b7f8cbc4a0570d16f4b7e!

Un-fork ScoutCamp, and upgrade a few other dependencies.

---

.gitignore
.travis.yml
api/admin-api.js
api/hosts-api.js
api/user-api.js
lib/hosts.js
package.json
tests/tests.js

This uses a semi-real Janitor server to mount the API, and runs all request/response examples against their respective handlers.
The only fake things are:
- A pre-registered `admin@example.com` admin user,
- A few simplified values (e.g. `.gitconfig` just contains `"[user]\nname = User"`),
- Some methods from `lib/docker.js` (because it's hard to test against a real Docker Remote API daemon or mock server)

Automatically test the Janitor API against its own request/response examples.

---

lib/docker.js
lib/machines.js

This change makes Janitor use the internal Docker tag `:janitor-production` for image updates and container spawns.
Previously, the default tag `:latest` was used for that, which caused the need for base images to use a different tag (e.g. `:base`).
As previously discussed on IRC, this wasn't convenient for most Docker Hub users out there wishing to add their projects to Janitor. So this change replaces the internal tag of `:latest` with an explicit `:janitor-production`, and allows using any base image tag instead of `:base` (i.e. you can now call base images `:latest`, or `:nightly`, or `:stable`, or `:1.0.5`, or anything you like except `:janitor-production`).
Note: The reason we need an external tag and an internal tag that's different is for building incremental image updates (we …

Tag internal Docker images with ':janitor-production'.

---

app.js
lib/machines.js
static/js/admin.js
templates/admin-projects.html

We can now use `Pull` to download up-to-date project Docker images from Docker Hub, instead of building them ourself. (We were doing that manually anyway, since our admin interface doesn't support local `ADD` Dockerfile instructions).
It's still possible to build incremental update layers using the `Update` button, and this can be a good option to provide more frequent project updates and save disk space by limiting the number of different base image versions used in production.

Remove deprecated project rebuild feature.

---

app.js
join.js
lib/proxy-heuristics.js
lib/users.js

We should remove them once Let's Encrypt supports wildcard certificates:
https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html
They should become available around January 2018, and will allow us to enforce
explicit proxy requests by specifying container ID and port in domains like:
'https://8088.abc123.<hostname>/index.html'
instead of the prefixed URLs we use today (which don't work with WebSockets):
'https://<hostname>/abc123/8080/index.html'

Add temporary proxy heuristics to mitigate ambiguous requests.

---

app.js

Small bit of fall out from #124, which was affecting WebSocket proxy requests to janitor.technology itself (so remote servers like moz1.janitor.technology weren't affected).

Fix local proxy by routing WebSocket requests to mapped ports.

---

api/hosts-api.js
lib/docker.js

These administrator-only API handlers will be useful in order to find out what's taking so much disk space on a Docker host.
I'm hoping to use it in a follow-up pull request to build a Docker admin interface that shows which images and containers take up the most disk space (e.g. as a tree), and that allows inspecting containers (to see if they contain anything valuable) and deleting them if they're useless to free up disk space.

Add an API to list Docker images and containers on a host.

---

static/css/janitor.css
static/js/admin.js
static/js/janitor.js
templates/admin-hosts.html

The Docker hosts administration section became read-only when the old Ajax API was deprecated.
This change updates it to the new JSON API using `window.fetch`, and is helpful to manage Docker hosts (e.g. to add new remote hosts, or to update the TLS certificates, etc).
@nt1m, please have a look to double-check I haven't made any mistakes, or forgotten anything while updating this page. (In theory, it works, because I was successful at using it locally to set up and remote control janitor.technology's Docker host).

Make the Docker host administration page editable again.

---

templates/contributions.html

We consider that every Janitor container, based on an image that was updated after August 2nd 2017, will ship with a working Cloud9 SDK running on port 8089.
However, we allow for a smooth transition period, by keeping a link to access Cloud9 SSH workspaces on the third-party service https://c9.io until September 1st 2017.
After September 1st, any pre-existing c9.io SSH workspaces will still work, but we'd like our users to not create new ones, and use the Cloud9 SDK on port 8089 instead (which is both faster to load and more stable).
Eventually, we'd like to stop relying on the https://c9.io third-party service, in order to support only our customized Cloud9 SDK. This will greatly simplify user registration, container creation, IDE access, IDE customization (with automated workflows for …

Transition Cloud9 IDE links from c9.io to the SDK installed in each container.

---

static/css/janitor.css

Margin creates ^ gap between the jumbotron and alert div, which doesn't look right.
After removing margin:

Removed margin from alert divs

---

api/user-api.js
app.js
lib/github.js
lib/routes.js
lib/users.js
templates/admin-header.html
templates/admin-integrations.html
templates/settings-integrations.html

When enabling the GitHub integration, the following profile data is imported:
- Username (public)
- Full name (public)
- SSH public keys (public)
We also plan to import verified email addresses in the future in order to
de-duplicate user accounts.

Allow users to import basic account information from GitHub.

---

api/hosts-api.js
lib/docker.js
static/css/janitor.css
static/js/admin.js
templates/admin-docker.html
tests/tests.js

The new documentation entry looks like this:
Here is what the feature looks like when you inspect filesystem changes in a given container from the Docker administration interface:
EDIT: All paths are now sorted alphabetically.

Add a feature to list changed files in a container (docker diff).

---

app.js
lib/routes.js
static/css/janitor.css
static/js/projects.js
templates/containers.html
templates/header.html
templates/projects-hint.html

This PR addresses part of #59, renaming Contributions to Containers and also redirecting from contributions to containers. 
Upon scanning the repository with Cloud 9, I found that `/dockerfiles/ubuntu-dev/client-workspace-janitor.js` has a [reference](https://github.com/JanitorTechnology/dockerfiles/blob/master/ubuntu-dev/workspace-janitor.js#L27) to contributions but I was unsuccessful in adding it to the PR. Would it be better to commit this to the [dockerfiles repository](https://github.com/JanitorTechnology/dockerfiles/)?

Rename Contributions to Containers

---

static/css/janitor.css
static/js/janitor.js

Title elements in the "Blog" and "API" pages already have unique `id` attributes.
This pull request adds small "#" links to facilitate referencing specific titles inside a page.

Add helpful anchor links to title elements with an 'id' attribute.

---

lib/users.js

This is a small regression from a previous refactor of user emails (it only slightly affects Janitor users during development, but it's still nice to fix it).
@nt1m could you please have a look? 😄

Fix allowing admin users to sign in without invitation.

---

api/blog-api.js
api/index.js
app.js
lib/blog.js
lib/routes.js
static/css/janitor-new.css
static/js/janitor-new.js
templates/blog-new.html

How it works
=========
Create the topic in the Newsletter category. If you don't tag it as `#published`, it won't show up. Once you tag it as published (and only staff have permission to tag a topic as published), it will show up on Janitor's blog page.
Also, the webhook payload is not read, and the signature is not validated. So you can manually trigger a poll by pointing your browser at that URL.
Importing old entries
=========
The "slug" in Discourse, which can be seen in the URL, becomes the `#id` of the post on Janitor (for example, the slug of this topic is `newsletters-composed-in-discourse-and-published-in-janitor`). If you don't want to break old links, make sure the post title will result in a correct slug.
Also, you can click the admin wrench and change the topic timestamp. The …

Implement a Discourse-backed blog page

---

lib/machines.js

If you enabled the GitHub integration, you probably have a few `[Object object]` in your containers' `~/.ssh/authorized_keys` files.
This is because SSH public keys imported from GitHub look like `{ id: 1, key: "ssh-rsa AAA..." }` instead of just `"ssh-rsa AAA..."`.

Fix GitHub SSH public keys in ~/.ssh/authorized_keys.

---

.janitor.json

Now that we repeat explicit commands between `()` in c9runner names, we can make the actual script names more descriptive.

Tweak janitor.json scripts.

---

lib/routes.js
package.json
templates/containers-new.html
templates/containers.html
templates/project.html
templates/projects.html

Drive-by changes:
- Update container title anchors to 16-char container IDs
- s/Updated/Built/ and s/build-time/pull-time/ in hidden project page

Add timeago server-side and use it to pre-render live-updating fuzzy timestamps.

---

templates/project.html
templates/projects.html

Because otherwise it clutters the projects list on the landing and projects pages. (Was #244.)

Move project descriptions to the project-specific page template.

---

app.js
lib/routes.js
static/css/janitor-new.css
templates/data-new.html

New data page

---

templates/configurations/.gitignore

** can only be a path component, not a part of filename.

Remove invalid gitignore entry

---

join.js
lib/proxy-heuristics.js

Theia uses the page URL as the WS endpoint, thus it has to be rewritten. ~Adding to that WebSocket handshakes get a Referer, so our logic just works.~
Some regex related code are modified for clarity (discard variables we don't care, so the variable doesn't have multiple meanings).

Fix WebSocket URL rewriting

---

templates/configurations/.gitignore

See: https://facebook.github.io/watchman/docs/config.html
I think we're going to integrate watchman to improve speed of VCS. This is the first step forward.

gitignore: add watchman config

---

lib/machines.js

Otherwise, Docker might pull all available image tags:
"Tag or digest. If empty when pulling an image, this causes all tags for the
given image to be pulled."
Source: https://docs.docker.com/engine/api/v1.24/#create-an-image

Always use an explicit tag when pulling a Docker image.

---

templates/configurations/.hgrc

It makes it easier to go through the list of patches as it shows the summary as well.

Add --summary by default for qseries and qunapplied

---

api/admin-api.js
app.js
join.js
lib/events.js
tests/tests.js

This is basically a re-work of https://github.com/JanitorTechnology/janitor/pull/140/ (sorry for the duplicate work!), which will allow us to schedule potentially long-term system events like "invalidate this token in 24 hours", "delete this container in 1 year", etc.
Here are the differences between this implementation and the "tasks" approach:
- I felt that using an `EventEmitter` was better-suited for registering + triggering callbacks on specific task/event types.
- I also regularly process upcoming tasks/events, but if they're due before the next loop, I use `setTimeout` to trigger them just in time.
- My approach doesn't need a unique task/event IDs.
- It supports multiple listeners for the same event type.
- It doesn't check for errors from the listeners (just if at least one …

Allow scheduling system events persistently.

---

app.js

Examples from our logs:
```
[2018-07-24T08:16:47.030Z] 404 /projects-new/
[2018-07-24T08:16:47.649Z] 404 /about/
[2018-07-24T08:16:47.996Z] 404 /projects-new
[2018-07-24T08:16:51.123Z] 404 /reference/api-new/
[2018-07-24T08:16:51.510Z] blog
[2018-07-24T08:16:52.020Z] 404 /settings-new/
[2018-07-24T08:16:55.996Z] 404 /blog-new/
```

Redirect old /*-new/ URLs to the right place.

---

README.md

DataDog -> Datadog

---

lib/machines.js

There is no need to make users wait for Docker when removing a container.
We can quickly remove it from the user's account, then wait for Docker to finish
cleaning up in the background. If cleaning up fails, we log the error and save
container ID and host, so that we can try again later.

UX: Make deleting containers faster and more consistent.

---

lib/machines.js

Currently, deleting a container works (fast) in the UI, but the backend containers are not actually removed.
This commit fixes the logical bug.

Fix faster container delete logic.

---

app.js

Drive-by: make a few other redirections permanent.
I didn't make the legacy settings redirections permanent, because one day I'd like to be able to address a specific settings tab, e.g. with a URL like `/settings/#configurations`.

Properly redirect legacy settings URLs.

---

lib/docker.js

Non-controversial parts split out of #315 (i.e. everything except `seccomp=unconfined`).

Enable debugger support for containers
